theme = "vanilla-bootstrap-hugo-theme"
baseURL = "2022-01-stat-complemento.netlify.app"
languageCode = "en-us"
title = "Estadística I. Herramientas de análisis"


# Uncomment below to enable syntax hghlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "MDR"
    pre = "MDR"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Teoría y práctica"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Code"
    pre = "maths"
    url = "/code/"
    weight = 3
  [[menu.nav]]
    name = "Bases de datos"
    pre = "smile"
    url = "/Bases de datos/"
    weight = 4
  [[menu.nav]]
    name = "Notación"
    pre = "rss"
    url = "/Notación"
    weight = 5  
  [[menu.nav]]
    name = "Material"
    pre = "aka"
    url = "/Material"
    weight = 6
[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Maestría en Desarrollo Regional. Estadística I. 2022-01."
  footerText = "José Luis Manzanares Rivera. 2022"
  hideFooter = false
  math= true