---
title: ""
author: "JLMR"
date: "13/1/2021"
output: html_document
---



```{r set-global-options, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = FALSE, 
                      cache = FALSE,
                      include = TRUE,
                      collapse = FALSE,
                      dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = FALSE)                     

```






```{r silent-packages, echo = FALSE, eval = TRUE, message=FALSE, include = FALSE}

library(ggplot2)
library(tidyverse)
```


## Herramientas de análisis y visualización 
### Código replicable. 


Sesión 3 [Series de tiempo y lineas de regresión](https://drive.google.com/file/d/1Ii-DgP75uBrundOXbbJeBUt0txgsVVL0/view?usp=sharing)

Sesión 3 [Rango intercuartil, percentiles y outliers: Boxplot](https://drive.google.com/file/d/1LRW5wcoLipsXGRtOC_CT7PxmOr0CgneD/view?usp=sharing)


Sesión 4  [Funciones de densidad para analizar distribución hipótesis](https://drive.google.com/file/d/1qXdI9rvPlBYu0OVYfDalNcsnoYJiPb5O/view?usp=sharing)


Sesión 4 práctica [scatter prueba de hipótesis](https://drive.google.com/file/d/1FfJUZPpmVmbxi73_1BXOCIo557LyBcZP/view?usp=sharing)