---
title: "Density"
author: "Jose´Luis Manzanares Rivera"
date: 2019-01-11T21:13:14-05:00
categories: ["R"]
tags: ["Density", "Distribution"]
---

```{r set-global-options, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = FALSE, 
                      cache = FALSE,
                      include = TRUE,
                      collapse = FALSE,
                      dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = FALSE)                     

```


```{r silent-packages, echo = FALSE, eval = TRUE, message=FALSE, include = FALSE}

library(ggplot2)
library(dplyr)
```


```{r,  fig.height = 8, fig.width = 12, message=FALSE, warning=FALSE}

sdensity<-readRDS("density.rds")%>%
  mutate(s=as.factor(s))%>%
  filter(ENT_RESID!=33& ENT_RESID!=34& ENT_RESID!=35& ENT_RESID!=99)%>%
  group_by(ENT_RESID)

cat_e<-read.csv("cat_entidad.csv")%>%
select(-X)%>%
rename(ent_res=X.U.FEFF.EDO)%>%
mutate(ent_res=sprintf("%02d",ent_res))%>%
mutate(ENT_RESID=as.factor(ent_res))%>%
select(-ent_res)

sdensity<-left_join(sdensity,cat_e)


mxplt<-ggplot(sdensity, aes(x=age,linetype=s, color=s))+
geom_line(stat="density")+
labs(linetype="Causa")+
xlab("Edad de la persona (Años)")+
ylab("Densidad f(y)")+
facet_wrap(~DESCRIP, nrow=6)+
scale_linetype(labels=c("Otras causas","Suicidio"))+
  theme_classic()+
scale_color_manual(values = c("mediumturquoise","magenta1"))+
  theme(legend.position="none")

mxplt
```


####  Caso Aguascalientes


```{r,  fig.height = 8, fig.width = 12,  message=FALSE, warning=FALSE}

ags<-filter(sdensity,ENT_RESID=="01")%>%
  mutate(s=as.factor(s))


aplt<-ggplot(ags, aes(x=age,linetype=s, color=s))+
geom_line(stat="density")+
labs(linetype="Causa")+
xlab("Edad de la persona (Años)")+
ylab("Densidad f(y)")+
annotate("segment", x=29, xend=13, y=0.011, yend=0.011,  size=.3, arrow=arrow(length=unit(.2,"cm")))+
annotate("text", x=23, y=0.013, label="Alta incidencia")+
annotate("text", x=21, y=0.009, label="13<Edad<29")+
annotate("rect", xmin=13, xmax=29, ymin=0, ymax=0.03, alpha=.1,fill="black")+
scale_linetype(labels=c("Otras causas","Suicidio"))+
theme_classic()+
scale_color_manual(values = c("mediumturquoise","magenta1"))+
theme(legend.position="none")


aplt

```
